name: Deploy to Vercel
on:
  push:
    branches: [main]  # 触发分支
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: pnpm install
      - name: Install Vercel CLI
        run: pnpm install -g vercel@latest
      - name: Deploy
        run: vercel --prod --yes --token ${{ secrets.ZXWIN_BLOG_VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.ZXWIN_BLOG_VERCEL_TOKEN }}